"""Build research/catalogue/INDEX.md from the family card files.

Reads only the card text (no market data, no results). Best-effort field parsing: the scouts
formatted a few fields differently, so unparsed values are shown as '?' rather than guessed.
Run: python3 research/catalogue/build_index.py
"""
import re
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
FAMILIES = ["trend", "mean_reversion", "breakout_vol", "cross_sectional", "carry_premia",
            "calendar_events", "flow_positioning", "patterns_levels", "models_regimes"]


def field(block: str, name: str) -> str:
    m = re.search(r"\*\*" + name + r"[^*]*\*\*[.:]?\s*(.*?)(?=\n- \*\*|\Z)", block, re.S)
    return m.group(1).strip() if m else ""


rows = []
for fam in FAMILIES:
    text = (HERE / f"{fam}.md").read_text()
    for blk in re.split(r"(?m)^(?=### S-)", text):
        h = re.match(r"### (S-[A-Z]+-\d+)\s*[·:\-]?\s*(.*)", blk)
        if not h:
            continue
        cid, name = h.group(1), h.group(2).strip()
        fid = re.search(r"\*\*Fidelity[^*]*\*\*[.:]?\s*([ABC])", blk)
        prim = field(blk, "Primitive")
        pm = re.search(r"[Pp]rimary[^P]{0,40}?(P\d+(?:-[\w]+)?)", prim) or re.search(r"(P\d+(?:-[\w]+)?)", prim)
        appl = field(blk, "Applies to")
        tm = re.search(r"\b(Y|N|[Pp]artial)\b", appl)
        rows.append(dict(fam=fam, id=cid, name=name[:70], fid=fid.group(1) if fid else "?",
                         prim=pm.group(1) if pm else "?", test=(tm.group(1).capitalize() if tm else "?"),
                         recalled=len(re.findall(r"recalled, not re-fetched", blk))))

out = ["# Catalogue index (phase 0)", "",
       "Generated by `research/catalogue/build_index.py` from the card files. Outcome-blind: nothing here is a result.",
       "Fidelity A = primary source with exact rules, B = secondary description, C = folklore or not mechanizable.",
       "'Testable here' is the scout's own judgement of whether our data can test the card (Y / Partial / N); '?' = not parsed.",
       "'Recalled' = the number of source claims in the card taken from memory and not re-fetched.", ""]
out += [f"Cards: {len(rows)}", ""]
fc = defaultdict(Counter)
for r in rows:
    fc[r["fam"]][r["fid"]] += 1
out += ["## By family and fidelity", "", "| family | cards | A | B | C | ? |", "|---|---|---|---|---|---|"]
for fam in FAMILIES:
    c = fc[fam]
    out.append(f"| {fam} | {sum(c.values())} | {c['A']} | {c['B']} | {c['C']} | {c['?']} |")
pc = defaultdict(Counter)
for r in rows:
    pc[r["prim"]][r["fid"]] += 1
out += ["", "## By primary primitive (the primitive map)", "", "| primitive | cards | A | B | C | testable Y |", "|---|---|---|---|---|---|"]
for p in sorted(pc):
    n = sum(pc[p].values())
    ty = sum(1 for r in rows if r["prim"] == p and r["test"] == "Y")
    out.append(f"| {p} | {n} | {pc[p]['A']} | {pc[p]['B']} | {pc[p]['C']} | {ty} |")
out += ["", "## All cards", "", "| id | name | fidelity | primary | testable here | recalled |", "|---|---|---|---|---|---|"]
for r in rows:
    out.append(f"| {r['id']} | {r['name']} | {r['fid']} | {r['prim']} | {r['test']} | {r['recalled']} |")
(HERE / "INDEX.md").write_text("\n".join(out) + "\n")
print(len(rows), "cards indexed")
print("unparsed fidelity:", sum(r["fid"] == "?" for r in rows), " unparsed primitive:", sum(r["prim"] == "?" for r in rows),
      " unparsed testable:", sum(r["test"] == "?" for r in rows))
