"""Merge the nine research/catalogue/probes/*.json files into a deduplicated probe library.

Outcome-blind: reads only the probe records (no market data). Writes
research/catalogue/PROBE_LIBRARY.md and research/catalogue/probes/library.json.
Run: python3 research/catalogue/build_probe_library.py
"""
import glob
import json
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
KEYS = {"probe_id", "card", "primitive", "horizon_band", "archetype", "variable", "params", "holds", "bar",
        "universe", "direction_claim", "data_needed", "testable_here", "regime_hypothesis_tags",
        "duplicate_of", "not_a_probe_reason", "note"}
ARCH = {"TS_STATE", "XS_RANK", "CLOCK", "EVENT", "CARRY", "FLOW_STATE", "VOL_STATE", "LEVEL_TOUCH", "MODEL", "NONE"}

rows = []
for f in sorted(glob.glob(str(HERE / "probes" / "[a-z]*.json"))):
    if f.endswith("library.json"):
        continue
    for r in json.load(open(f)):
        assert set(r) == KEYS, (f, r.get("probe_id"), set(r) ^ KEYS)
        assert r["archetype"] in ARCH, (r["probe_id"], r["archetype"])
        rows.append(r)

ids = [r["probe_id"] for r in rows]
assert len(ids) == len(set(ids)), "duplicate probe_id"
real = [r for r in rows if r["archetype"] != "NONE"]
none = [r for r in rows if r["archetype"] == "NONE"]


def tcode(r):
    return (r["testable_here"] or "?").split(":")[0].strip()


groups = defaultdict(list)
for r in real:
    groups[(r["archetype"], r["variable"])].append(r)


def union(rs, key):
    out = []
    for r in rs:
        v = r["params"].get(key) if isinstance(r["params"], dict) else None
        if isinstance(v, list):
            out += [x for x in v if x not in out]
    return out


lib = []
for (arch, var), rs in sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    t = Counter(tcode(r) for r in rs)
    lib.append(dict(archetype=arch, variable=var, n_probes=len(rs), cards=sorted({r["card"] for r in rs}),
                    probe_ids=[r["probe_id"] for r in rs],
                    primitives=sorted({str(r["primitive"]) for r in rs}),
                    bars=sorted({str(r["bar"]) for r in rs}),
                    universes=sorted({str(r["universe"]) for r in rs}),
                    data_needed=sorted({d for r in rs for d in r["data_needed"]}),
                    lookbacks=union(rs, "lookbacks"), thresholds=union(rs, "thresholds"),
                    holds=sorted({h for r in rs for h in r["holds"]}),
                    testable=dict(t), runnable=t["Y"] > 0))
json.dump(lib, open(HERE / "probes" / "library.json", "w"), indent=1)

run = [g for g in lib if g["runnable"]]
parked = [g for g in lib if not g["runnable"]]
out = ["# Probe library (phase 1b)", "",
       "Generated by `build_probe_library.py` from `probes/*.json`. Outcome-blind: no market data was opened.",
       "A probe group is one (archetype, variable). 'Runnable' = at least one of its probes is testable on the",
       "public crypto archive (scout code Y); the rest are parked with the missing data named.", "",
       f"- Probe records: {len(rows)} from {len({r['card'] for r in rows})} cards; {len(none)} are NONE (no probe).",
       f"- Real probes: {len(real)} in {len(lib)} unique (archetype, variable) groups; {len(run)} runnable, {len(parked)} parked.",
       "", "## By archetype (real probes / groups / runnable groups)", "",
       "| archetype | probes | groups | runnable groups |", "|---|---|---|---|"]
for a in sorted({g["archetype"] for g in lib}):
    gs = [g for g in lib if g["archetype"] == a]
    out.append(f"| {a} | {sum(g['n_probes'] for g in gs)} | {len(gs)} | {sum(g['runnable'] for g in gs)} |")
out += ["", "## NONE records (why no probe)", "", "| probe | reason |", "|---|---|"]
for r in none:
    out.append(f"| {r['probe_id']} | {r['not_a_probe_reason']} |".replace("\n", " "))
out += ["", "## Runnable groups", "", "| archetype | variable | probes | cards | bars | testable Y/Partial/N |", "|---|---|---|---|---|---|"]
for g in run:
    t = g["testable"]
    out.append(f"| {g['archetype']} | {g['variable']} | {g['n_probes']} | {len(g['cards'])} | {','.join(g['bars'])} | {t.get('Y',0)}/{t.get('Partial',0)}/{t.get('N',0)} |")
out += ["", "## Parked groups (no probe testable on the crypto archive)", "", "| archetype | variable | probes | data needed |", "|---|---|---|---|"]
for g in parked:
    out.append(f"| {g['archetype']} | {g['variable']} | {g['n_probes']} | {', '.join(g['data_needed'])} |")
(HERE / "PROBE_LIBRARY.md").write_text("\n".join(out) + "\n")
print(len(rows), "records;", len(real), "real probes;", len(lib), "groups;", len(run), "runnable;", len(parked), "parked;", len(none), "NONE")
